package com.revive.enums;

/**
 * How a recovery probability prediction was generated
 */
public enum PredictionMethod {
    /**
     * Generated by trained ML model (Random Forest, Gradient Boosting, etc.)
     */
    ML_MODEL,
    
    /**
     * Generated by rule-based fallback logic
     */
    RULE_BASED,
    
    /**
     * Fallback when ML model unavailable or failed
     */
    FALLBACK
}
